server:
  #  端口号
  port: 9000

spring:
  # 应用名称
  application:
    name: robot
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/robot?userUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: password
  #redis的配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 5
    timeout: 5000

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/com/yww/robot/mapper/xml/*.xml
